### ISSUE TITLE
Apollo 1, globally handle data.error errors with 200 HTTP code status. Not the network one.

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1444]
**Intended outcome:**

Catch globally the `data.error`, like when `react-apollo` tells me this:

```
Unhandled (in react-apollo) Error: GraphQL error: Not authorized for Query.myQuery
    at new ApolloError (http://localhost:4000/static/js/bundle.js:3637:28)
    at ObservableQuery../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.currentResult (http://localhost:4000/static/js/bundle.js:1219:25)
    at GraphQL.dataForChild (http://localhost:4000/static/js/bundle.js:41273:62)
    at GraphQL.render (http://localhost:4000/static/js/bundle.js:41323:33)
    at finishClassComponent (http://localhost:4000/static/js/bundle.js:50012:31)
...
```

**Actual outcome:**

Actually I can handle globally error with this:

```
  networkInterface.useAfter([
    {
      applyAfterware({ response }, next) {
        console.log("response useAfter():", response);
        next();
      }
    }
  ]);
```

but this is good for the network error, not the GraphQL ones (like the authorization one) that are always 200 HTTP code status.

**Version**
- apollo-client@**1.9.x**
- react-apollo@**1.4.16**

**Comment by hwillson** [comment]
Please try the error handling in modern versions of Apollo Client / React Apollo, and post back if you're still having issues. Thanks!
