### ISSUE TITLE
Error when react router dom Link is clicked

### ISSUE THREAD

**Issue by fondberg** [apollographql/react-apollo#1760]
**Intended outcome:**
Using react router link from one GraphQL component to another will transition using react-router-link without error in the console.

**Actual outcome:**
It works but there is an exception in the console.
```
index.js:2177 Unhandled error GraphQL error: Exception while fetching data (/googleCloudPlatformProject) : Not found Error: GraphQL error: Exception while fetching data (/googleCloudPlatformProject) : Not found
    at new ApolloError (http://localhost:5678/static/js/bundle.js:73199:28)
    at http://localhost:5678/static/js/bundle.js:72246:41
    at http://localhost:5678/static/js/bundle.js:72627:17
    at Array.forEach (<anonymous>)
    at http://localhost:5678/static/js/bundle.js:72626:18
    at Map.forEach (<anonymous>)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:5678/static/js/bundle.js:72621:22)
    at Object.next (http://localhost:5678/static/js/bundle.js:72655:31)
    at SubscriptionObserver.next (http://localhost:5678/static/js/bundle.js:76491:14)
    at http://localhost:5678/static/js/bundle.js:73487:76
    at Array.forEach (<anonymous>)
    at Object.next (http://localhost:5678/static/js/bundle.js:73487:43)
    at SubscriptionObserver.next (http://localhost:5678/static/js/bundle.js:355307:20)
    at http://localhost:5678/static/js/bundle.js:73770:26
    at nrWrapper (http://localhost:5678/vendor/newrelic.js:514:26)
    at <anonymous>
__stack_frame_overlay_proxy_console__ @ index.js:2177
console.(anonymous function) @ console.js:32
observer._subscription._observer.error @ ObservableQuery.js:289
error @ zen-observable.js:174
./node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.onSubscribe @ ObservableQuery.js:296
(anonymous) @ ObservableQuery.js:37
Subscription @ zen-observable.js:103
subscribe @ zen-observable.js:229
./node_modules/react-apollo/react-apollo.browser.umd.js.ObservableQueryRecycler.recycle @ react-apollo.browser.umd.js:54
GraphQL.componentWillUnmount @ react-apollo.browser.umd.js:327
callComponentWillUnmountWithTimer @ react-dom.development.js:8732
callCallback @ react-dom.development.js:542
wrapped @ raven.js:353
nrWrapper @ newrelic.js:514
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
safelyCallComponentWillUnmount @ react-dom.development.js:8739
commitUnmount @ react-dom.development.js:8865
unmountHostComponents @ react-dom.development.js:9204
commitDeletion @ react-dom.development.js:9234
commitAllHostEffects @ react-dom.development.js:9926
callCallback @ react-dom.development.js:542
wrapped @ raven.js:353
nrWrapper @ newrelic.js:514
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10015
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
wrapped @ raven.js:353
nrWrapper @ newrelic.js:514
```

It seems related to https://github.com/apollographql/apollo-client/issues/2258 but I couldn't get 2.1.0-beta.3 working

**How to reproduce the issue:**
In a pure component which gets the data using recompose of `grapql(gql'query...')` add
```
<Link to="/projects-owned"><Button raised color="primary">List all my projects</Button></Link>
```
Where Link comes from react-router-dom and the app has the following HoC `ConnectedRouter > ApolloProvider`

**Version**

* apollo-client@2.2.5
* react-apollo@2.0.4 (tried with 2.1.0-beta.2 and 3 but got many errors )

**Comment by rosskevin** [comment]
Closing - housekeeping.  This looks better suited for stackoverflow.
