### ISSUE TITLE
Graphql query -- Error: Network error: Server response was missing for query 'undefined'. 

### ISSUE THREAD

**Issue by kierah** [apollographql/react-apollo#1825]
**Intended outcome:**
I'm trying to query a graphql service. I have an implementation that works that uses XHR, and I'm trying to migrate that over to graphql-tag and react-apollo.

This is the Component that is trying to query (you should be able to see both implementations there):
```import React, { Component } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import Post from './Post.js';
import './Blog.css';

const GRAPHQL_SERVER='http://localhost:4000/graphql'
const BLOG_QUERY0=gql`{
  allPosts(blogId: "blog-g2pc5150jesudoyn") {
    id
    blogId
    title
    text
    likes
  }
}`;

class Blog extends Component {
  constructor(props) {
    super(props);
    var xhr = new XMLHttpRequest();
    xhr.open("POST", GRAPHQL_SERVER);
    xhr.responseType = 'json';
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.setRequestHeader("Accept", "application/json");
    xhr.onload = this.onLoad.bind(this);

    var query = BLOG_QUERY0;
    console.log("sending query");
    xhr.send(JSON.stringify({
      query: query,
      variables: { id: props.blogId },
    }));
    this.state = {
      blogId: props.blogId,
      xhr: xhr,
    }
  }
  getData() {

  }
  onLoad() {
    let xhr = this.state.xhr;
    console.log('data returned:', xhr.response);
    console.log('this blog', this);
//    this.setState({
//      response: xhr.response,
//    });
  }

  render() {
    if (this.props.data.loading) {
      return (<div>Loading</div>);
    }

    console.log("render", this.props.data);

/*
{this.props.data.allPosts.map((post) =>
  <Post key={post.id} post={post} refresh={() => this.props.data.refetch()} />
)}  
*/
    return (
      <div className="blog-container">

      
      </div>

    );
  }
}

const BLOG_QUERY=gql`query AllPosts($blogId: String) {
  allPosts(blogId: $blogId) {
    id
    blogId
    title
    text
    likes
  }
}`;

export default graphql(BLOG_QUERY)(Blog)
```
This query works in graphiql and also in the XHR implementation:
```{
  allPosts(blogId: "blog-g2pc5150jesudoyn") {
    id
    blogId
    title
    text
    likes
  }
}
```

**Actual outcome:**

This produces the following error:
```
Unhandled (in react-apollo:Apollo(Blog)) Error: Network error: Server response was missing for query 'undefined'.
    at new ApolloError (http://localhost:3000/static/js/bundle.js:3637:28)
    at ObservableQuery../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.currentResult (http://localhost:3000/static/js/bundle.js:1219:25)
    at GraphQL.dataForChild (http://localhost:3000/static/js/bundle.js:19843:62)
    at GraphQL.render (http://localhost:3000/static/js/bundle.js:19893:33)
    at finishClassComponent (http://localhost:3000/static/js/bundle.js:28415:31)
    at updateClassComponent (http://localhost:3000/static/js/bundle.js:28392:12)
    at beginWork (http://localhost:3000/static/js/bundle.js:28767:16)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:30766:16)
    at workLoop (http://localhost:3000/static/js/bundle.js:30830:26)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:21084:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:21123:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:20980:27)
    at renderRoot (http://localhost:3000/static/js/bundle.js:30908:7)
    at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:31556:24)
    at performWork (http://localhost:3000/static/js/bundle.js:31509:7)
    at requestWork (http://localhost:3000/static/js/bundle.js:31420:7)
    at scheduleWorkImpl (http://localhost:3000/static/js/bundle.js:31274:11)
    at scheduleWork (http://localhost:3000/static/js/bundle.js:31231:12)
    at Object.enqueueForceUpdate (http://localhost:3000/static/js/bundle.js:26792:7)
    at GraphQL../node_modules/react/cjs/react.development.js.Component.forceUpdate (http://localhost:3000/static/js/bundle.js:45488:16)
    at GraphQL.forceRenderChildren (http://localhost:3000/static/js/bundle.js:19811:26)
    at next (http://localhost:3000/static/js/bundle.js:19786:27)
    at Object.handleError [as error] (http://localhost:3000/static/js/bundle.js:19790:32)
    at http://localhost:3000/static/js/bundle.js:1462:29
    at Array.forEach (<anonymous>)
    at Object.error (http://localhost:3000/static/js/bundle.js:1460:33)
    at http://localhost:3000/static/js/bundle.js:1855:38
    at http://localhost:3000/static/js/bundle.js:2341:25
    at Array.forEach (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:2338:27
    at Array.forEach (<anonymous>)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:3000/static/js/bundle.js:2335:42)
    at http://localhost:3000/static/js/bundle.js:1804:31
    at <anonymous>
```

**Version**

* apollo-client@5.6.0
* react-apollo@5.6.0
* graphql-tag@5.6.0

**Comment by kierah** [comment]
The problem turned out to be a wrong URI in code that looked like this:

```const GRAPHQL_SERVER='http://localhost:4000/graphql'

const networkInterface = createNetworkInterface({
  uri: GRAPHQL_SERVER
})
const client = new ApolloClient({
  networkInterface
})
```

Thanks for your time.
