### ISSUE TITLE
Mockprovider/Client is giving error "networkError: Error: Mocked response should contain either result or error ..."

### ISSUE THREAD

**Issue by DennisKo** [apollographql/react-apollo#1923]
**Intended outcome:**

I am trying to create a MockedClient+Provider to mock data based on a schema.json for testing.

```
// MockClient.js
import * as introspectionResult from '../../schema.json';
import ApolloClient from 'apollo-client';
import { buildClientSchema } from 'graphql';
import { addMockFunctionsToSchema } from 'graphql-tools';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { SchemaLink } from 'apollo-link-schema';
import { IntrospectionFragmentMatcher } from 'apollo-cache-inmemory';
import introspectionQueryResultData from './fragmentTypes.json';

// this creates a mocked apollo client for testing

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData
});

const cache = new InMemoryCache({ fragmentMatcher });

const schema = buildClientSchema(introspectionResult);

addMockFunctionsToSchema({
  schema,
  mocks: {
    DateTime: () => new Date()
  }
});

const mockedClient = new ApolloClient({
  cache,
  link: new SchemaLink({ schema })
});

export default mockedClient;
```

```
// App.test.js
function renderWithApollo(component, query) {
  return {
    ...render(
      <MockedProvider
        addTypename
        client={MockedClient}
        mocks={[
          {
            request: { query }
          }
        ]}
      >
        {component}
      </MockedProvider>
    )
  };
}

beforeEach(() => {
  wrapper = renderWithApollo(<App />, GetAllTodoItems);
});
```

It should provide the mocked data...

**Actual outcome:**

In the test I get the following error:

```
Error: Network error: Mocked response should contain either result or error: {"variables":{},"query":"query GetAllTodoItems {\n  allTodoItems {\n    id\n    title\n    updatedAt\n    createdAt\n  }\n}\n"}
          at new ApolloError (/Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:121:28)
          at ObservableQuery.Object.<anonymous>.ObservableQuery.currentResult (/Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:244:24)
          at Query._this.getQueryResult (/Users/dennisko/develop/react-apollo/node_modules/react-apollo/react-apollo.umd.js:319:59)
          at Query.Object.<anonymous>.Query.render (/Users/dennisko/develop/react-apollo/node_modules/react-apollo/react-apollo.umd.js:421:36)
          at finishClassComponent (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:8377:33)
          at updateClassComponent (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:8345:12)
          at beginWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:8966:16)
          at performUnitOfWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:11798:16)
          at workLoop (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:11827:26)
          at renderRoot (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:11858:9)
          at performWorkOnRoot (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12422:24)
          at performWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12343:9)
          at performSyncWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12320:5)
          at requestWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12220:7)
          at scheduleWorkImpl (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12095:13)
          at scheduleWork (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:12055:12)
          at Object.enqueueForceUpdate (/Users/dennisko/develop/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:6670:7)
          at Query.Object.<anonymous>.Component.forceUpdate (/Users/dennisko/develop/react-apollo/node_modules/react/cjs/react.development.js:260:16)
          at Query._this.updateCurrentData (/Users/dennisko/develop/react-apollo/node_modules/react-apollo/react-apollo.umd.js:314:27)
          at Object.error (/Users/dennisko/develop/react-apollo/node_modules/react-apollo/react-apollo.umd.js:302:31)
          at SubscriptionObserver.error (/Users/dennisko/develop/react-apollo/node_modules/zen-observable/zen-observable.js:178:20)
          at /Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:539:82
          at Array.forEach (<anonymous>)
          at Object.error (/Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:539:33)
          at /Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:1194:38
          at /Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:1620:17
          at Array.forEach (<anonymous>)
          at /Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:1619:18
          at Map.forEach (<anonymous>)
          at QueryManager.Object.<anonymous>.QueryManager.broadcastQueries (/Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:1614:22)
          at /Users/dennisko/develop/react-apollo/node_modules/apollo-client/bundle.umd.js:1114:31
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:160:7)
        graphQLErrors: [],
```

**How to reproduce the issue:**

https://github.com/DennisKo/react-apollo/tree/react-testing-library

This was working in react-apollo 2.1.0-beta.3

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3

**Comment by sbcreates** [comment]
`<MockedProvider>` expects the prop `mocks` to contain an array of the request and response.

You supply the request but not the response data it seems in your MockedProvider component.

Example from the [docs](https://www.apollographql.com/docs/react/api/react-apollo.html#MockedProvider):
```
const mocks = [
  {
    request: {
      query: SOME_QUERY,
      variables: { first: 4 }
    },
    result: {
      data: {
        dog: {
          name: "Douglas"
        }
      }
    }
  },
  {
    request: {
      query: SOME_QUERY,
      variables: { first: 8}
    },
    error: new Error("Something went wrong")
  }
]
```

**Comment by rosskevin** [comment]
Closing - housekeeping
