### ISSUE TITLE
Cannot read property 'scheduler' or undefined

### ISSUE THREAD

**Issue by stolinski** [apollographql/react-apollo#2235]
**Intended outcome:**

Component to unmount successfully via cleanup (I think it's just running ReactDOM.unmountComponentAtNode(container)) under the hood. 

**Actual outcome:**

```
    TypeError: Cannot read property 'scheduler' of undefined

      at MockedProvider.Object.<anonymous>.MockedProvider.componentWillUnmount (node_modules/react-apollo/test-utils.js:942:60)
      at callComponentWillUnmountWithTimer (node_modules/react-dom/cjs/react-dom.development.js:14280:12)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:138:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)
      at safelyCallComponentWillUnmount (node_modules/react-dom/cjs/react-dom.development.js:14287:5)
      at commitUnmount (node_modules/react-dom/cjs/react-dom.development.js:14494:11)
      at unmountHostComponents (node_modules/react-dom/cjs/react-dom.development.js:14796:7)
      at commitDeletion (node_modules/react-dom/cjs/react-dom.development.js:14827:5)
      at commitAllHostEffects (node_modules/react-dom/cjs/react-dom.development.js:15416:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:138:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:15568:7)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:16618:34)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16563:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16454:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16354:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16218:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16785:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16812:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16839:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17122:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17277:12)
      at node_modules/react-dom/cjs/react-dom.development.js:17335:9
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16679:10)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:17334:7)
      at cleanupAtContainer (node_modules/react-testing-library/dist/index.js:80:22)
          at Set.forEach (<anonymous>)
      at Object.cleanup (node_modules/react-testing-library/dist/index.js:71:21)
```

**How to reproduce the issue:**

Use https://github.com/kentcdodds/react-testing-library with MockedProvider and run afterEach(cleanup) as see in react-testing-library's docs.

A barebones failing example could look like. 

```
import React from 'react';
import { render, cleanup } from 'react-testing-library';
import { MockedProvider } from 'react-apollo/test-utils';
import Component from '../Component';

afterEach(cleanup);

test('<Component>', async () => {
  const wrapper = render(
    <MockedProvider mocks={[]}>
      <Component />
    </MockedProvider>
  );
});
```

**Version**

* apollo-client@2,3,5
* react-apollo@2.1.9

Seems like there was another issue 
https://github.com/apollographql/react-apollo/issues/2164
and a PR to fix this, but I'm not sure if the fixes made it into npm because I'm still seeing the error with 2.1.9

https://github.com/apollographql/react-apollo/pull/2165

**Comment by danilobuerger** [comment]
Duplicate of #2164

**Comment by stolinski** [comment]
I wasn't sure if I should comment on the closed issue or file a new one. Either way it looks like this issue is still present in 2.1.9.

**Comment by danilobuerger** [comment]
Thats because the fix was not released in 2.1.9 as it was merged after 2.1.9 was released. The fix is in master and will be in the next release. Either downgrade to 2.1.8 or use master until then. (Issue should be closed though)

**Comment by stolinski** [comment]
Gotcha. There was no indication of what version the fix would be in so I wasn't sure if the issue was still present or not. Closing.

**Comment by danilobuerger** [comment]
Sorry, my fault for not updating the changelog!
