### ISSUE TITLE
not work in IE11 with next.js

### ISSUE THREAD

**Issue by superbull** [apollographql/react-apollo#2260]
**Intended outcome:**

Should work in IE11

**Actual outcome:**

Error
```
Object doesn't support property or method 'assign'
TypeError: Object doesn't support property or method 'assign'
   at _this.getQueryResult (node_modules/react-apollo/react-apollo.browser.umd.js:362:0)
   at Query.prototype.render (node_modules/react-apollo/react-apollo.browser.umd.js:465:0)
   at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13193:0)
   at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13155:0)
   at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13824:0)
   at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15863:0)
   at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15902:0)
   at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15942:0)
   at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16560:0)
   at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:0)

```

**Investigation**

In the `package.json` file of react-apollo I found `"@types/object-assign": "4.0.30"` already added to the devDependencies, but why not also add `object-assign`?

**Version**

* apollo-client@2.3.7
* react-apollo@2.1.9

**Comment by rosskevin** [comment]
You will need to provide your own polyfills for your target browsers.
