### ISSUE TITLE
Error import react-apollo on aws serverless

### ISSUE THREAD

**Issue by KrifaYounes** [apollographql/react-apollo#2339]
node version : 8.10
On aws serverless with webpack I have got the error below when I used : 
`import {renderToStringWithData, ApolloProvider } from 'react-apollo';
`

the react-apollo is present on node_modules sended to aws

```
Unable to import module 'lambda': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at /var/task/node_modules/react-apollo/react-apollo.umd.js:2:152
at Object.<anonymous> (/var/task/node_modules/react-apollo/react-apollo.umd.js:5:2)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
```

**Comment by rosskevin** [comment]
This is not caused by react-apollo.
