### ISSUE TITLE
[getDataFromTree] Invariant Violation: Element type is invalid 

### ISSUE THREAD

**Issue by bradleykhan** [apollographql/react-apollo#3511]
Updating `react-apollo` as per recommendations to start using `useQuery` & `useMutation` hooks instead of render prop components `<Query>` & `<Mutation>`

**Intended outcome:**
Updating `react-apollo` from ^2.5.8 to 3.x.x (all versions tried)

**Actual outcome:**
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
GraphQL error occurred [getDataFromTree] Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at invariant (/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)
    at ReactDOMServerRenderer.render (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3443:7)
    at ReactDOMServerRenderer.read (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at process (/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16) {
  name: 'Invariant Violation',
  framesToPop: 1
}
```

**How to reproduce the issue:**
Update `react-apollo` from ^2.5.8 to 3.x.x

**Version**
3.0.0, 3.1.0, 3.1.1

**Futher Info**
There seems to be a lot of very similar issues currently with updating `react-apollo` into 3.x.x I've tried many of the suggestions. However I can't get beyond this issue. 

I've ensured all the peer dependencies of `react-apollo` are on the same version
![image](https://user-images.githubusercontent.com/34278008/65250523-94333900-daed-11e9-9ee0-1ab2e7e64e25.png)

`next-with-apollo` is updated to the latest version `4.3.0` which I believe is to support hooks.

Some help would be greatly appreciated!

```
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.2
  npmPackages:
    apollo-boost: ^0.4.3 => 0.4.3
    apollo-client: ^2.6.3 => 2.6.3
    next-with-apollo: ^4.3.0 => 4.3.0
    react-apollo: ^3.1.1 => 3.1.1
```

**Comment by talentlessguy** [comment]
Any progress on the issue? I hate render props and can't use hooks because of this
