### ISSUE TITLE
GraphQL validation fails on fragments that only have `@client` fields

### ISSUE THREAD

**Issue by lensbart** [apollographql/react-apollo#3650]
Greetings of the day

Queries that contain a fragment consisting only of scalar fields with the `@client` directive lead to the following error:

```
{
  "errors": [
    {
      "message": "Unknown fragment \"niceFragment\".",
      "locations": [
        {
          "line": 73,
          "column": 6
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "GraphQLError: Unknown fragment \"niceFragment\".",
            "    at Object.FragmentSpread (node_modules/graphql/validation/rules/KnownFragmentNames.js:29:29)",
            "    at Object.enter (node_modules/graphql/language/visitor.js:324:29)",
            "    at Object.enter (node_modules/graphql/language/visitor.js:375:25)",
            "    at visit (node_modules/graphql/language/visitor.js:242:26)",
            "    at Object.validate (node_modules/graphql/validation/validate.js:73:24)",
            "    at validate (node_modules/apollo-server-core/dist/requestPipeline.js:212:32)",
            "    at Object.<anonymous> (node_modules/apollo-server-core/dist/requestPipeline.js:125:42)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (node_modules/apollo-server-core/dist/requestPipeline.js:5:58)"
          ]
        }
      }
    }
  ]
}
```

Including at least one non-`@client` field avoids the error.

**Comment by dylanwulf** [comment]
I think this is a duplicate of https://github.com/apollographql/apollo-client/issues/5192
