### ISSUE TITLE
Development: issue running SSR test, due to what-wg fetch

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-apollo#375]
I don't understand why we don't see this in CI, and I'm not sure if anyone else is seeing it ( @jbaxleyiii ?).

When I run tests locally, "SSR › `renderToStringWithData` › should work on a non trivial example" fails, throwing a network error with the following stack:

```
       TypeError: Network request failed
           at XMLHttpRequest.xhr.onerror (/Users/tom/Apollo/react-apollo/node_modules/apollo-client/node_modules/whatwg-fetch/fetch.js:433:16)
           at XMLHttpRequest.callback.(anonymous function) (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:289:32)
           at invokeEventListeners (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
           at invokeInlineListeners (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:166:7)
           at EventTargetImpl._dispatch (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:122:7)
           at EventTargetImpl.dispatchEvent (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
           at XMLHttpRequest.dispatchEvent (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
           at dispatchError (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:946:9)
           at validCORSHeaders (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:961:7)
           at receiveResponse (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:834:12)
           at Request.client.on.res (/Users/tom/Apollo/react-apollo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:662:38)
           at emitOne (events.js:96:13)
           at Request.emit (events.js:188:7)
           at Request.onRequestResponse (/Users/tom/Apollo/react-apollo/node_modules/request/request.js:986:10)
           at emitOne (events.js:101:20)
           at ClientRequest.emit (events.js:188:7)
           at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
           at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
           at Socket.socketOnData (_http_client.js:363:20)
           at emitOne (events.js:96:13)
           at Socket.emit (events.js:188:7)
           at readableAddChunk (_stream_readable.js:176:18)
           at Socket.Readable.push (_stream_readable.js:134:10)
           at TCP.onread (net.js:548:20) }
```

It seems incorrect to me that it uses `whatwg-fetch` rather than `isomorphic-fetch` for this request, but then I can't explain why it works for all other SSR tests. Is the request timing out from here in Australia?

**Comment by tmeasday** [comment]
Actually, I suppose the reason all the other SSR tests work is that they use a mocked network interface.

**Comment by jbaxleyiii** [comment]
@tmeasday I don't seem to have this issue locally? However we should actually mock all of these requests instead of relying on an external app

**Comment by tmeasday** [comment]
Agreed, although maybe there's something to be said for having a test that goes through the whole stack.

I wondered if you had any clues as to why the request would be sent through jsdom, given this is a SSR test? Is there something we need to change in the Jest setup to make it not mock `window` et al?

OTOH it might be easier to just do the mocking, not sure.

**Comment by jbaxleyiii** [comment]
@tmeasday prior to this being in jest, I couldn't figure out a way to separate the evn. With jest, we could use jest.mock to force isomorphic for this test. I'd be happy to open that as a PR

**Comment by jbaxleyiii** [comment]
With #353 this should be better. Closing this for tracking progress there
