### ISSUE TITLE
Error in QueryManager when id is not queried for nested item.

### ISSUE THREAD

**Issue by richburdon** [apollographql/react-apollo#385]
When querying for a nested item, if the "id" field is not requested the errors below are observed.

const TaskFragment = gql`
  fragment TaskFragment on Task {
    bucket 
    project {
      id                  // ERROR if omitted
      title
    }
  }
`;

[main] Error: Network error: Store error: the application attempted to write an object with no provided id but the store already contains an id of Project/demo for this object.

QueryManager.js?2cbe:150 Error in observer.error 
Error
    at new ApolloError (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4420:2), <anonymous>:31:23)
    at eval (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4426:2), <anonymous>:141:39)
    at eval (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4426:2), <anonymous>:629:25)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4426:2), <anonymous>:626:27)
    at eval (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:3502:2), <anonymous>:17:11)
    at baseForOwn (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:3490:2), <anonymous>:13:20)
    at forOwn (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4438:2), <anonymous>:33:20)
    at QueryManager.broadcastQueries (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4426:2), <anonymous>:624:9)
    at QueryManager.broadcastNewStore (eval at <anonymous> (http://localhost:3000/assets/hot.bundle.js:4426:2), <anonymous>:63:14)

**Comment by tmeasday** [comment]
Hi @richburdon, I suspect this is an issue better opened on the https://github.com/apollostack/apollo-client repo. Are you using `dataIdFromObject`? If so does it require `id` to be set?

**Comment by cesarsolorzano** [comment]
Closing up old issues
