### ISSUE TITLE
Jest tests failed whenever ApolloProvider is imported

### ISSUE THREAD

**Issue by vhmh2005** [apollographql/react-apollo#841]
**Intended outcome:**
I'm using jest for testing. The simple test like this should pass:
```js
import { ApolloProvider } from 'react-apollo';
test('true', () => { expect(true).toBe(true); });
``` 
**Actual outcome:**
However, I got this error
```sh

 TypeError: Cannot read property 'ReactCurrentOwner' of undefined

   at Object.<anonymous> (node_modules/react-apollo/node_modules/react-dom/cjs/react-dom-server.development.js:3534:33)
   at Object.<anonymous> (node_modules/react-apollo/node_modules/react-dom/server.js:6:16)
   at graphqlTag (node_modules/react-apollo/lib/react-apollo.umd.js:2:176)
   at Object.<anonymous> (node_modules/react-apollo/lib/react-apollo.umd.js:5:3)
```
![image](https://user-images.githubusercontent.com/877578/28125242-389ab626-6750-11e7-9796-852235d14727.png)

**How to reproduce the issue:**
This is trivial as in the screenshot above
**Version**
- apollo-client@1.8.0
- react-apollo@1.4.3

**Comment by blargity** [comment]
I believe this is the same as #826.

**Comment by jbaxleyiii** [comment]
This will be fixed with the new release today
